keybinds:
  bindings:
    "0": "debugInfo"
    "Escape": "pauseMenu"
    "A": "walkLeft"
    "S": "walkBackward"
    "D": "walkRight"
    "Tab": "onlinePlayers"
    "W": "walkForward"
    "Enter": "chat"
clientUUID: 7
playerName: "sam"
language: "English"